### ISSUE TITLE
Summer 2019 Road Map

### ISSUE THREAD

**Issue by dustinnewman98** [dustinnewman98/wych#23]
- [ ] Fix Quill toolbar bug
- [ ] Quill editor should have white bg
- [ ] Create a document and allocate all proper Google Drive documents/folders
  - [ ] If slug already exists, then create a new article under existing article set
  - [ ] If slug is unique, then create a new article set and then the new article
  - [ ] Also create the headlines.json file for headline threading
- [ ] Figure out some debounced/throttled way to push edits to Storage Manager OR require manual saving
- [ ] Editor view should have different modes for (regular articles and galleries) and (flatpage views)
  - [ ] On the "new article" modal, create a way to create different article types
  - [ ] Then on creating the article in the `ArticleController` create the data.aml file appropriately
  - [ ] For the page editor view, the Quill editor does not need to support rich text. Plain text is fine. But collaborative editing must be maintained
  - [ ] For the page editor view, create a "generate preview" button which will show them the JSON way their AML is being interpreted
- [ ] Implement editable user profile page
  - [ ] Users should be able to add/edit their Caeruleum credentials (create a `pressPass` row)
- [ ] Implement assignment control flow (i.e. a contributor can request edits from editor who can reject or send to copy, if the article is in copy, only copy should be able to edit the document)
- [ ] Implement uploading images to S3 bucket (this should have the same abstraction as the Storage Manager has where you can upload to S3 or the local file system)
- [ ] Desk functionality (fetch all articles assigned to the current user and also fetch all articles in the same group as that user (that are not published))

**Comment by dustinnewman98** [comment]
priv group: 6f54696

**Comment by dustinnewman98** [comment]
apikey name/medium fields: e55f19a

**Comment by dustinnewman98** [comment]
smpost: d5bd393

**Comment by dustinnewman98** [comment]
desk: 5e1e447

**Comment by dustinnewman98** [comment]
create docs/folders: 6c302f2ef201eea255d72e6d6137905a14aed160

**Comment by dustinnewman98** [comment]
desk datatable --> table: 1b1380c5605bf298f2b410aeba14583daad295ad

**Comment by dustinnewman98** [comment]
editable profile adds `presspass`: 6f2a0c5

**Comment by dustinnewman98** [comment]
editable profile: b5272f6

**Comment by dustinnewman98** [comment]
delete presspass and corresponding apikeys: 85dd34b

**Comment by dustinnewman98** [comment]
leave section: 783b66d488e2c7e8914bb486411ef8b13c9206c6

**Comment by dustinnewman98** [comment]
quill fixes in general: 720807f
